# Mod info
mod_name=Particle Generator
mod_jar_name=ParticleGenerator
mod_id=pgen
mod_group=com.mt1006.pgen
mod_author=mt1006
version=1.1
license=LGPL-3.0-only
homepage=https://modrinth.com/mod/particlegenerator
source_url=https://github.com/mt1006/mc-pgen-mod
issue_tracker=https://github.com/mt1006/mc-pgen-mod/issues
mod_description=Adds Particle Generator, which is highly customizable block that allows you to generate multiple particles at a specific position.

# Minecraft and Java
minecraft_version=1.20.4
java_version=17

# Requires
version_range_fabric=>=1.20.3 <1.20.5
version_range_forge=[1.20.3,1.20.5)

# Loaders
# https://github.com/FabricMC/fabric-loader/releases
# https://modrinth.com/mod/fabric-api/versions?c=release
# https://files.minecraftforge.net/net/minecraftforge/forge/
fabric_loader_version=0.16.9
fabric_api_version=0.97.2+1.20.4
forge_version=49.1.0

# Mappings
# https://parchmentmc.org/docs/getting-started
parchment_minecraft=1.20.4
parchment_version=2024.04.14

# Gradle dependencies
# https://github.com/FabricMC/fabric-loom/releases
# https://files.minecraftforge.net/net/minecraftforge/gradle/ForgeGradle/index.html
fabric_loom_version=1.9-SNAPSHOT
forge_gradle_version=[6.0.29,6.2)

# Gradle configuration
org.gradle.jvmargs=-Xmx3G
org.gradle.daemon=false
org.gradle.problems.report=false
