# Mod info
mod_name=Particle Generator
mod_jar_name=ParticleGenerator
mod_id=pgen
mod_group=com.mt1006.pgen
mod_author=mt1006
version=1.1
license=LGPL-3.0-only
homepage=https://modrinth.com/mod/particlegenerator
source_url=https://github.com/mt1006/mc-pgen-mod
issue_tracker=https://github.com/mt1006/mc-pgen-mod/issues
mod_description=Adds Particle Generator, which is highly customizable block that allows you to generate multiple particles at a specific position.

# Minecraft and Java
minecraft_version=1.21.1
java_version=21

# Requires
version_range_fabric=>=1.21 <1.21.2
version_range_forge=[1.21.1,1.21.2)
version_range_neoforge=[1.21,1.21.2)

# Loaders
# https://github.com/FabricMC/fabric-loader/releases
# https://modrinth.com/mod/fabric-api/versions?c=release
# https://files.minecraftforge.net/net/minecraftforge/forge/
# https://projects.neoforged.net/neoforged/neoforge
fabric_loader_version=0.16.9
fabric_api_version=0.110.0+1.21.1
forge_version=52.0.28
neoforge_version=21.1.90

# Mappings
# https://parchmentmc.org/docs/getting-started
parchment_minecraft=1.21.1
parchment_version=2024.11.17

# Gradle dependencies
# https://github.com/FabricMC/fabric-loom/releases
# https://files.minecraftforge.net/net/minecraftforge/gradle/ForgeGradle/index.html
# https://projects.neoforged.net/neoforged/ModDevGradle
fabric_loom_version=1.9-SNAPSHOT
forge_gradle_version=[6.0.29,6.2)
neoforge_moddev_version=2.0.61-beta

# Gradle configuration
org.gradle.jvmargs=-Xmx3G
org.gradle.daemon=false
org.gradle.problems.report=false
