org.gradle.jvmargs=-Xmx3G
org.gradle.daemon=false

minecraft_version=1.21.3
neoforge_version=21.3.4-beta

minecraft_version_range=[1.21.2,)

neogradle.subsystems.parchment.minecraftVersion=1.21
neogradle.subsystems.parchment.mappingsVersion=2024.07.07


## Mod Properties
mod_id=pgen
mod_version=1.0.3

mod_group_id=com.mt1006.pgen
mod_jar_name=ParticleGenerator

mod_name=ParticleGenerator
mod_license=LGPL-3.0-only

mod_authors=mt1006
mod_description=Adds particle generator.
mod_url=https://github.com/mt1006/mc-pgen-mod
mod_issues=https://github.com/mt1006/mc-pgen-mod/issues