modLoader="javafml"
loaderVersion="[44,)"
license="GNU Lesser General Public License v3.0"

[[mods]]
modId="pgen"
version="1.0.1"
displayName="ParticleGenerator"
logoFile="logo.png"
authors="mt1006 (mt1006x)"
description="Just particle generator"

[[dependencies.pgen]]
    modId="forge"
    mandatory=true
    versionRange="[45,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.pgen]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.19.4,1.20)"
    ordering="NONE"
    side="BOTH"
