plugins
{
	id "net.minecraftforge.gradle" version "${forge_gradle_version}"
}

minecraft
{
	mappings channel: "official", version: minecraft_version

	runs
	{
		client
		server
	}
}

dependencies
{
	minecraft "net.minecraftforge:forge:${minecraft_version}-${forge_version}"
}

sourceSets.each
{
	def dir = layout.buildDirectory.dir("sourcesSets/$it.name")
	it.output.resourcesDir = dir
	it.java.destinationDirectory = dir
}
