plugins
{
	id "net.minecraftforge.gradle" version "${forge_gradle_version}"
}

minecraft
{
	mappings channel: "official", version: minecraft_version
	reobf = false

	runs
	{
		client
		server
	}
}

dependencies
{
	minecraft "net.minecraftforge:forge:${minecraft_version}-${forge_version}"
	implementation("net.sf.jopt-simple:jopt-simple:5.0.4") { version { strictly "5.0.4" } }
}

sourceSets.each
{
	def dir = layout.buildDirectory.dir("sourcesSets/$it.name")
	it.output.resourcesDir = dir
	it.java.destinationDirectory = dir
}
